# Set the port for the API Gateway. This is the single entry point for our frontend.
server:
  port: 8080

# Give our Spring application a name.
spring:
  application:
    name: api-gateway

  # Configure the routing rules for Spring Cloud Gateway.
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Apply this configuration to all paths
            allowed-origins: "http://localhost:5173" # Allow requests from our React dev server
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowed-headers: "*" # Allow all standard headers

      default-filters:
        - AuthenticationFilter
      routes:

        # --- Route for the Authentication Service ---
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/auth/**

        # --- Route for the Employee Service ---
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/employees/**, /api/v1/departments/**, /api/v1/salaries/**

        # --- Route for the Project Service ---
        - id: project-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/projects/**, /api/v1/assignments/**

        # --- Route for the Feedback Service ---
        - id: feedback-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/feedback/**

        # --- Route for the Reporting Service ---
        - id: reporting-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/reports/**

# ===============================================================
# Custom Properties for JWT Token Validation
# ===============================================================
# This MUST be the exact same secret key used in the auth-service
jwt:
  secret: tStyos9C0YBcfjpcYQf74BLL0x2/CHA+E3xb17dNU6hy2NY+5u2S98+vSs66e5CJFyIG60CoiVXe190rBL2QfA==